folio-org/mod-finc-config

- src/main/java/org/folio/finc/select/MetadataCollectionsHelper.java
- src/main/java/org/folio/finc/select/MetadataSourcesHelper.java
- src/main/java/org/folio/finc/select/isil/filter/IsilFilter.java
- src/main/java/org/folio/finc/select/isil/filter/MetadataCollectionIsilFilter.java
- src/main/java/org/folio/finc/select/isil/filter/MetadataSourcesIsilFilter.java
- src/test/java/org/folio/finc/select/isil/filter/MetadataCollectionIsilFilterTest.java
- src/test/java/org/folio/finc/select/isil/filter/MetadataSourcesIsilFilterTest.java
> Add meaningful error msg when isil is not found

- ramls/examples/fincSelectMetadataCollection.sample
- ramls/examples/fincSelectMetadataCollection_collection.sample
> FOLIO-601 Fix broken JSON examples RAML

- .gitignore
If it does not interfere with anything, target (plus some auxiliary files) may be ignored.
> ignore auxiliary files

- ramls/fincConfigMetadataCollections.raml
- ramls/fincConfigMetadataSources.raml
- ramls/fincSelectFilters.raml
- ramls/fincSelectMetadataCollections.raml
- ramls/fincSelectMetadataSources.raml
Add examples to raml files.
While it's helpful for reviewers to help identify potential …
> Add examples to raml files

- ramls/schemas/fincConfigMetadataCollection.json
- ramls/schemas/fincConfigMetadataSource.json
- ramls/schemas/fincSelectFilter.json
- ramls/schemas/fincSelectMetadataCollection.json
- ramls/schemas/fincSelectMetadataSource.json
- src/main/resources/templates/db_scripts/schema.json
Add metadata (record last created/updated) to metadata sources, metadata collections and filters.
Add metadata.schema from raml-util to schema definitions of corresponding entities.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to …
> Add metadata to collections, sources, and filters

- ramls/examples/fincConfigMetadataCollection_collection.sample
- ramls/examples/fincConfigMetadataSource_collection.sample
- ramls/examples/fincSelectFilter1.sample
- ramls/examples/fincSelectFilter2.sample
Update sample files so that documentation is in an correct state.
While it's helpful for …
> Update sample files

- pom.xml
- src/main/java/org/folio/finc/dao/FilterToCollectionsDAOImpl.java
- src/main/java/org/folio/finc/dao/MetadataSourcesDAOImpl.java
- src/main/java/org/folio/finc/dao/SelectFileDAOImpl.java
- src/main/java/org/folio/finc/dao/SelectFilterDAOImpl.java
- src/main/java/org/folio/finc/select/FilterHelper.java
- src/test/java/org/folio/finc/ApiTestSuite.java
- src/test/java/org/folio/finc/select/FilterHelperTest.java
- src/test/java/org/folio/finc/select/SelectMetadataSourceVerticleTest.java
- src/test/java/org/folio/finc/select/SelectMetadataSourceVerticleTestHelper.java
- src/test/java/org/folio/finc/select/SelectMetadataSourcesHelperTest.java
- src/test/java/org/folio/finc/select/UnselectMetadataSourceVerticleTest.java
While it's helpful for reviewers to help identify potential problems, ensuring that it's …
> Uifc 168 upgrade rmb v30

- src/main/resources/templates/db_scripts/migration/1.6.0/metadata_collections.sql
- src/main/resources/templates/db_scripts/schema.json
While it's helpful for reviewers to help identify potential problems, ensuring that it's …
> Add migrate script for md collections

- ramls/examples/fincConfigMetadataSource.sample
- ramls/examples/fincConfigMetadataSource2.sample
- ramls/examples/fincSelectMetadataSource.sample
- ramls/examples/fincSelectMetadataSource_collection.sample
- ramls/schemas/fincConfigMetadataSource.json
- ramls/schemas/fincSelectMetadataSource.json
- sample-data/finc-config/metadata-sources/cambridge_university_press_journals.json
- sample-data/finc-config/metadata-sources/early_music_online.json
- src/main/resources/templates/db_scripts/migration/1.6.0/metadata_collections.sql
- src/main/resources/templates/db_scripts/migration/1.6.0/migrate_to_1_6_0.sql
- src/main/resources/templates/db_scripts/schema.json
While it's helpful for reviewers to help identify potential problems, ensuring that it's …
> Remove contracts from metadata sources

- ramls/examples/fincConfigMetadataSource_collection.sample
- ramls/schemas/fincConfigMetadataSource.json
- ramls/schemas/fincSelectMetadataSource.json
- src/test/java/org/folio/finc/select/SelectMetadataSourcesIT.java
While it's helpful for reviewers to help identify potential problems, ensuring that it's …
> Update possible values for status

- descriptors/ModuleDescriptor-template.json
- pom.xml
- ramls/examples/contact.sample
- ramls/examples/contact_collection.sample
- ramls/examples/fincConfigMetadataSource.sample
- ramls/examples/fincConfigMetadataSource2.sample
- ramls/examples/fincConfigMetadataSource_collection.sample
- ramls/examples/fincSelectMetadataSource.sample
- ramls/examples/fincSelectMetadataSource_collection.sample
- ramls/fincConfigMetadataSources.raml
- ramls/schemas/contact.json
- ramls/schemas/contacts.json
- ramls/schemas/fincConfigMetadataSource.json
- ramls/schemas/fincSelectMetadataSource.json
- sample-data/finc-config/metadata-sources/cambridge_university_press_journals.json
- sample-data/finc-config/metadata-sources/early_music_online.json
- src/main/java/org/folio/finc/dao/MetadataSourcesDAO.java
- src/main/java/org/folio/finc/dao/MetadataSourcesDAOImpl.java
- src/main/java/org/folio/rest/impl/FincConfigContactsAPI.java
- src/main/resources/templates/db_scripts/migration/3.0.0/migrate_to_3_0_0.sql
- src/main/resources/templates/db_scripts/schema.json
- src/main/resources/templates/db_scripts/views.sql
- src/test/java/org/folio/finc/ApiTestBase.java
- src/test/java/org/folio/finc/ApiTestSuite.java
- src/test/java/org/folio/finc/config/AbstractMetadataSourcesIT.java
- src/test/java/org/folio/finc/config/ConfigContactsIT.java
- src/test/java/org/folio/finc/config/ConfigMetadataSourcesIT.java
[UIFC-181](https://issues.folio.org/browse/UIFC-181) defines the re-design of the contacts of metadata-sources.
This PR changes the contacts structure and adds an endpoint to GET the defined contacts.
> [UIFC-181] Restructure contacts

- pom.xml
- src/main/java/org/folio/finc/model/File.java
- src/main/java/org/folio/rest/impl/FincConfigContactsAPI.java
- src/main/java/org/folio/rest/impl/FincConfigTinyMetadataSourcesAPI.java
and update some other dependencies
> [UIFC-347] Update to RMB v35.2.0, Vert.x v4.5.4

- descriptors/ModuleDescriptor-template.json
- pom.xml
https://folio-org.atlassian.net/browse/UIFC-383
> [UIFC-383] Update interface names per folio naming convention

- .github/workflows/postgres.yml
- pom.xml
- ramls/fincConfigEZBCredentials.raml
- ramls/fincConfigFiles.raml
- ramls/fincConfigFilters.raml
- ramls/fincConfigMetadataCollections.raml
- ramls/fincConfigMetadataSources.raml
- ramls/fincSelectEZBCredentials.raml
- ramls/fincSelectFiles.raml
- ramls/fincSelectFilters.raml
- ramls/fincSelectMetadataCollections.raml
- ramls/fincSelectMetadataSources.raml
- ramls/isils.raml
- src/main/java/org/folio/rest/impl/FincConfigContactsAPI.java
- src/main/java/org/folio/rest/impl/FincConfigEZBCredentialsAPI.java
- src/main/java/org/folio/rest/impl/FincConfigFiltersAPI.java
- src/main/java/org/folio/rest/impl/FincConfigMetadataCollectionsAPI.java
- src/main/java/org/folio/rest/impl/FincConfigMetadataSourcesAPI.java
- src/main/java/org/folio/rest/impl/FincConfigTinyMetadataSourcesAPI.java
- src/main/java/org/folio/rest/impl/FincSelectFiltersAPI.java
- src/main/java/org/folio/rest/impl/FincSelectMetadataCollectionsAPI.java
- src/main/java/org/folio/rest/impl/FincSelectMetadataSourcesAPI.java
- src/main/java/org/folio/rest/impl/IsilsAPI.java
- src/main/java/org/folio/rest/impl/Messages.java
https://folio-org.atlassian.net/browse/UIFC-382
* Update RMB, vert.x, aspectj versions
* Update raml-util
* Update API method parameters (remove `lang`, add `totalRecords`)
* Add GA postgres workflow
> [UIFC-382] Upgrade RMB to v35.3.0

- ramls/fincConfigMetadataSources.raml
- ramls/fincSelectMetadataCollections.raml
- ramls/fincSelectMetadataSources.raml
- ramls/rtypes/item-collection-put.raml
- src/main/java/org/folio/rest/impl/FincConfigContactsAPI.java
- src/main/java/org/folio/rest/impl/FincConfigTinyMetadataSourcesAPI.java
- src/main/java/org/folio/rest/impl/FincSelectMetadataCollectionsAPI.java
- src/main/java/org/folio/rest/impl/FincSelectMetadataSourcesAPI.java
- src/test/java/org/folio/finc/select/SelectMetadataCollectionsIT.java
- src/test/java/org/folio/finc/select/SelectMetadataSourcesIT.java
https://folio-org.atlassian.net/browse/UIFC-393
* Clean up. Remove unimplemented/unused API endpoints.
* Fix RAML definitions so they dont declare unrequired endpoints.
> [UIFC-393] Remove unimplemented/unused API methods

- descriptors/ModuleDescriptor-template.json
- pom.xml
https://folio-org.atlassian.net/browse/UIFC-392
* Updated permissions
* Removed unimplemented endpoint from Module Descriptor
```
removed:
"finc-select.metadata-collections.item.filters"
renamed:
"finc-select.metadata-collections.item.select" -> "finc-select.metadata-collections.item.select.item.put"
"finc-select.metadata-sources.item.select-all" -> "finc-select.metadata-sources.item.collections.select-all.item.put"
additional:
"finc-config.filters.item.get" -> "finc-config.filters.item.collections.item.get"
"finc-config.filters.item.put" -> "finc-config.filters.item.collections.item.put"
"finc-config.metadata-sources.collection.get" -> "finc-config.contacts.collection.get"
"finc-config.metadata-sources.collection.get" -> "finc-config.tiny-metadata-sources.collection.get" …
```
> [UIFC-392] Review and cleanup Module Descriptor

- NEWS.md
- pom.xml
https://folio-org.atlassian.net/browse/UIFC-397
Release v6.0.0
> [UIFC-397] Release v6.0.0

- README.md
- descriptors/ModuleDescriptor-template.json
- pom.xml
- src/main/java/org/folio/finc/periodic/EZBHarvestJob.java
- src/main/java/org/folio/finc/periodic/ezb/EZBServiceImpl.java
- src/main/java/org/folio/rest/impl/PostDeployImpl.java
- src/main/java/org/folio/rest/utils/Constants.java
- src/test/java/org/folio/finc/ApiTestSuite.java
- src/test/java/org/folio/finc/PostDeployImplITest.java
- src/test/java/org/folio/finc/TenantITest.java
- src/test/java/org/folio/finc/periodic/EZBHarvestJobITest.java
- src/test/java/org/folio/finc/periodic/ezb/EZBServiceImplTest.java
- src/test/java/org/folio/finc/select/SelectMetadataSourceVerticleTest.java
- src/test/java/org/folio/finc/select/SelectMetadataSourcesHelperTest.java
- src/test/java/org/folio/finc/select/UnselectMetadataSourceVerticleTest.java
https://folio-org.atlassian.net/browse/UIFC-398
* Introduces a environment variable `EZB_DOWNLOAD_URL` that should be used to set the EZB URL
> [UIFC-398] Make EZB URL configurable

- pom.xml
- src/main/java/org/folio/finc/periodic/ezb/EZBServiceImpl.java
Fix logging scope and log initialization
> [UIFC-398] Fix logging scope and log initialization

- src/test/java/org/folio/finc/PostDeployImplITest.java
https://folio-org.atlassian.net/browse/UIFC-407
> [UIFC-407] Fix test deployment port

- src/main/java/org/folio/rest/FincConfigLauncher.java
https://folio-org.atlassian.net/browse/UIFC-406
> [UIFC-406] Increase maximum allowed string length for RMBs ObjectMapper

- Dockerfile
- Jenkinsfile
- pom.xml
https://folio-org.atlassian.net/browse/UIFC-420
* Upgrades to Java 21
* Updates maven dependencies
> [UIFC-420] Upgrade to Java 21

- NEWS.md
- pom.xml
https://folio-org.atlassian.net/browse/UIFC-421
> [UIFC-421] Release v6.1.0

- ramls/isils.raml
- src/main/java/org/folio/finc/dao/IsilDAO.java
- src/main/java/org/folio/finc/dao/IsilDAOImpl.java
- src/main/java/org/folio/finc/select/SelectMetadataCollectionsHelper.java
- src/main/java/org/folio/rest/impl/FincConfigIsilsAPI.java
- src/main/java/org/folio/rest/impl/FincSelectEZBCredentialsAPI.java
- src/main/java/org/folio/rest/impl/FincSelectFilesAPI.java
- src/main/java/org/folio/rest/impl/FincSelectFiltersAPI.java
- src/main/java/org/folio/rest/impl/FincSelectMetadataCollectionsAPI.java
- src/main/java/org/folio/rest/impl/FincSelectMetadataSourcesAPI.java
- src/main/java/org/folio/rest/impl/IsilsAPI.java
- src/test/java/org/folio/ApiTestBase.java
- src/test/java/org/folio/ITTestSuiteJunit4.java
- src/test/java/org/folio/ITTestSuiteJunit5.java
- src/test/java/org/folio/TestUtils.java
- src/test/java/org/folio/finc/config/ConfigMetadataCollectionsWithFiltersIT.java
- src/test/java/org/folio/finc/dao/IsilDAOTest.java
- src/test/java/org/folio/finc/select/IsilsIT.java
- src/test/java/org/folio/rest/impl/FincConfigIsilsIT.java
https://folio-org.atlassian.net/browse/UIFC-268
* Make IsilDAO return an empty Optional instead of `null`
* Update tests
* Minor refactorings and renames
* Add `422` response to `PUT` method in `isils.raml`
> [UIFC-268] Make IsilDAO return empty Optional instead of null
